# Generated by Django 5.0 on 2023-12-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ganho',
            field=models.IntegerField(null=True),
        ),
    ]
