# Generated by Django 5.0 on 2023-12-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0002_member_ganho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ganho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('ganhou', 'Ganhou'), ('perdeu', 'Perdeu'), ('pendente', 'Pendente')], max_length=20),
        ),
    ]
