# Generated by Django 5.0 on 2023-12-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0003_alter_member_ganho_alter_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='odd',
            field=models.IntegerField(),
        ),
    ]
