# Generated by Django 5.0 on 2023-12-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0004_alter_member_odd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='odd',
            field=models.FloatField(),
        ),
    ]
