# Generated by Django 5.0 on 2023-12-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0005_saldo_alter_member_odd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganho', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
