# Generated by Django 5.0 on 2023-12-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0006_aposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lucros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lucro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='ganho',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
