# Generated by Django 5.0 on 2023-12-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0007_lucros_alter_member_ganho_alter_member_valor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lucros',
        ),
        migrations.AddField(
            model_name='member',
            name='lucros',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
