# Generated by Django 5.0 on 2023-12-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0008_delete_lucros_member_lucros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='lucros',
            field=models.DecimalField(decimal_places=2, default='DEFAULT VALUE', max_digits=5, null=True),
        ),
    ]
