# Generated by Django 5.0 on 2023-12-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0009_alter_member_lucros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='lucros',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5, null=True),
        ),
    ]
