# Generated by Django 5.0 on 2023-12-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0010_alter_member_lucros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='lucros',
        ),
    ]
