# Generated by Django 5.0 on 2023-12-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0011_remove_member_lucros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lucros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lucros', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
