# Generated by Django 5.0 on 2023-12-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0012_lucros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lucros',
        ),
    ]
