# Generated by Django 5.0 on 2023-12-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0013_delete_lucros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
