# Generated by Django 5.0 on 2023-12-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucros', '0014_alter_saldo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='casa',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
